fos_rest:
    serializer:
        serialize_null: true
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        enabled: true
        rules:
            # ... previous rules declarations
            - { path: '^/admin', stop: true }  # <-- add this line
            - { path: '^/login', stop: true }
            - { path: '^/logout', stop: true }
            - { path: '^/', stop: true }
    view:
        view_response_listener: force
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json