<?php

namespace AppBundle\Repository;

/**
 * logActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogActionRepository extends \Doctrine\ORM\EntityRepository
{
}
