<?php

namespace AppBundle\Repository;

/**
 * LogTypeManualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogTypeManualRepository extends \Doctrine\ORM\EntityRepository
{
}
