<?php

namespace AppBundle\Repository;

/**
 * NoteContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteContactRepository extends \Doctrine\ORM\EntityRepository
{
}
