<?php

namespace AppBundle\Repository;

/**
 * NoteBusinessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteBusinessRepository extends \Doctrine\ORM\EntityRepository
{
}
