<?php

namespace AppBundle\Repository;

/**
 * NoteCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteCompanyRepository extends \Doctrine\ORM\EntityRepository
{
}
