<?php

namespace AppBundle\Repository;

/**
 * PipelineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PipelineRepository extends \Doctrine\ORM\EntityRepository
{
}
