<?php

namespace AppBundle\Repository;

/**
 * PipelineStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PipelineStateRepository extends \Doctrine\ORM\EntityRepository
{
}
