<?php

namespace AppBundle\Repository;

/**
 * RecurrenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecurrenceRepository extends \Doctrine\ORM\EntityRepository
{
}
