<?php

namespace AppBundle\Repository;

/**
 * StudyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudyRepository extends \Doctrine\ORM\EntityRepository
{
}
