<?php

namespace AppBundle\Repository;

/**
 * TaskStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskStateRepository extends \Doctrine\ORM\EntityRepository
{
}
