# Aca hago expose de las propiedades que quiero que se muestren del FOSUserBundle
FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [profile, basic_user, login]
        username:
            expose: true
            groups: [profile, basic_user, login]
        email:
            expose: true
            groups: [profile, login, basic_user]
        roles:
            expose: false
        enabled:
            expose: false
        confirmationToken:
            expose: false
        deleted:
            expose: false
