nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['X-BIKIP-APIKEY', 'Content-Type']
        allow_methods: ['POST', 'PATCH', 'GET', 'DELETE']
        max_age: 3600
        hosts: []
        origin_regex: false
nelmio_api_doc: ~