#listeners here
services:
    json_exception_listener:
        class: ApiBundle\ExceptionListener\JsonExceptionListener
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
