services:
    kodear_api.entities_service:
        class: ApiBundle\Service\EntitiesService
        abstract: true
        arguments: 
            #- '@api_security.api_key_user_provider'
            #- %register_confirmation_required%
        calls:
            - [setApiKeyUserProvider, ['@api_security.api_key_user_provider']]
            - [setContainer, ['@service_container']]
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
            - [setHelperService, ['@kodear_api.helper_service']]
            - [setFormFactory, ['@form.factory']]
            #- [setRegisterConfirmationRequired, [%register_confirmation_required%]]
            #- [setTokenGenerator, ['@fos_user.util.token_generator']]

    kodear_api.helper_service:
        class: ApiBundle\Service\HelperService
        parent: kodear_api.entities_service
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    kodear_api.form_errors_service:
        class: ApiBundle\Service\FormErrorsService

    kodear_api.email_messages_service:
        class: ApiBundle\Service\EmailMessagesService
        arguments:
            - '@service_container'
            - '@mailer'
            - '@doctrine.orm.entity_manager'

    kodear_api.base64_service:
        class: ApiBundle\Service\Base64ToUploadedFile
        arguments:
            - '@service_container'

    kodear_api.user_service:
        class: ApiBundle\Service\UserService
        parent: kodear_api.entities_service
        calls:
            - [setRegisterConfirmationRequired, [%register_confirmation_required%]]
            - [setTokenGenerator, ['@fos_user.util.token_generator']]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


